### ISSUE TITLE
Time required for each drop.

### ISSUE THREAD

**Issue by ChocolatFolie** [webben-de/ASF_ItemDropper#13]
Hello, I don't know if it's just me, but the drops take far too long, between 2 and 4 times longer than normal (without ASF)... Is there any way to configure this?

**Comment by Sniper677** [comment]
If IDROP command is executed, it sends a trigger to Steam and if all requirements are fulfilled (minimum time since last drop + minimum playtime since last drop) Steam drops an item to inventory. That's all. Therefore I don't see an issue here.

The plugin has no automatic mode as some other tools have. This might be the difference.

**Comment by ChocolatFolie** [comment]
Oh okay...
